version: '3'

services:
  api:
    build: .

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 80:8080
      - 443:8080
